docker login docker.pkg.github.com --username SH0-ahacker

docker tag IMAGE_ID docker.pkg.github.com/SH0-ahacker/zolatted/IMAGE_NAME:VERSION

docker push docker.pkg.github.com/SH0-ahacker/zolatted/IMAGE_NAME:VERSION
